// <auto-generated />
using System;
using FirstProject.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FirstProject.Backend.Data.Migrations
{
    [DbContext(typeof(EmployeeSalaryAppContext))]
    [Migration("20241104172823_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("FirstProject.Backend.Entities.EmployeeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MonthSalary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("YearInWhichHeWorkedId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("yearId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("yearId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("FirstProject.Backend.Entities.YearEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("IncomeTaxPercentage")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InsurancePercantage")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaximumInsuranceThreshold")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinimumThreshold")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Years");
                });

            modelBuilder.Entity("FirstProject.Backend.Entities.EmployeeEntity", b =>
                {
                    b.HasOne("FirstProject.Backend.Entities.YearEntity", "year")
                        .WithMany()
                        .HasForeignKey("yearId");

                    b.Navigation("year");
                });
#pragma warning restore 612, 618
        }
    }
}
